version: "3.8"

services:
  postgresql:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "7878"
    ports:
      - "5432:5432"

